### ISSUE TITLE
gfx_graphics depends on itself

### ISSUE THREAD

**Issue by csherratt** [PistonDevelopers/gfx_graphics#236]
`piston_window` window needs `gfx_graphics` Which means is `gfx_graphics` is broken you can't compile any of the examples. Overriding `gfx_graphics` does not work even via the `paths` variable.

**Comment by bvssvni** [comment]
There is also the problem that gfx_graphics can't be published on crates.io because piston_window is not updated, but when trying to update piston_window cargo complains about gfx_graphics.

**Comment by kvark** [comment]
but piston_window is a dev dependency, so cargo shouldn't look for it when publishing, right?

**Comment by mitchmindtree** [comment]
I think this should be ok as piston_window "0.0.0" is already on crates.io, so we could probably use that as the dev-dependency just to get gfx_graphics on crates.io first, then update piston_window, and then update gfx_graphics to the latest piston_window? This should work, right?

**Comment by LaylConway** [comment]
That's an old piston_window version on crates.io though, and it looks like it's using git dependencies.

**Comment by mitchmindtree** [comment]
I'm going to remove the examples from gfx_graphics temporarily, upload 0.1.20, then update piston_window's crate, then add the examples back in and update to 0.1.21

**Comment by mitchmindtree** [comment]
I thought that #245 would solve this issue by getting both on crates.io, however it doesn't. The issue that still remains is:
- Once #245 lands, we need to update piston_window to use gfx_graphics `0.1.21`.
- When we have, we then have to increment the version of piston_window so that we can publish it with the new gfx_graphics dependency version.
- Once we do that, we'd then have to update gfx_graphics to use the latest piston_window, meaning we'd then have to increment the version of gfx_graphics...
- etc, etc, eternally.

I'm not sure how we can fix this other than remove the dependency from one or the other?

Perhaps a good solution would be to move the gfx_graphics examples to the [piston_examples repo](https://github.com/pistondevelopers/piston-examples)?

**Comment by bvssvni** [comment]
Moving the examples is a good idea.
